---
- name: update web servers
  hosts: all
  task:
    - os_image:
        auth:
          auth_url: https://identity.example.com
          username: admin
          password: password
          project_name: Automation
          os_user_domain_name: Default
          os_project_domain_name: Default
        name: cirros
        container_format: bare
        disk_format: qcow2	
        state: present
        filename: cirros-0.3.0-x86_64-disk.img
        kernel: cirros-vmlinuz
        ramdisk: cirros-initrd
        properties:
          cpu_arch: x86_64
          distro: ubuntu

